server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: create-candidate
