spring:
  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: complete-calculation
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      topic: create-candidate
      group-id: calculation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

app:
  min-salary: 40000
  junior-middle-threshold: 100000
  middle-senior-threshold: 200000
  max-salary: 1000000
