spring:
  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis

kafka:
  consumer:
    topic: create-candidate
    group-id: calculation-group
  producer:
    topic: complete-calculation
